"""Added Tables

Revision ID: 271e5ed1bfe2
Revises: 5f4e509eef98
Create Date: 2024-11-13 11:02:31.223296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271e5ed1bfe2'
down_revision = '5f4e509eef98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service__req',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=256), nullable=False),
    sa.Column('assign_prof', sa.Integer(), nullable=True),
    sa.Column('req_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assign_prof')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=256), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=256), nullable=False),
    sa.Column('contact_no', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_status')
    op.drop_table('services')
    op.drop_table('service__req')
    # ### end Alembic commands ###
