"""Added Tables

Revision ID: 5f4e509eef98
Revises: 
Create Date: 2024-11-13 01:53:12.836084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4e509eef98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed__services', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed__services', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
