"""added table

Revision ID: 8be78e7548ac
Revises: 271e5ed1bfe2
Create Date: 2024-11-13 11:53:28.523821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be78e7548ac'
down_revision = '271e5ed1bfe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin__search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_professional', sa.String(length=255), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin__search')
    # ### end Alembic commands ###
